### PR TITLE
Puppet v4 support

### PR DESCRIPTION
**Pull request by propyless**
Fixes spec tests to run for all version using the standard used by stdlib functions
Puppet v4 module type declaration used

### CODE REVIEW

**Comment by leoleovich** [comment]
+1

**Comment by xepa** [comment]
Any chance this will get pulled ?

**Comment by Kyoshiro-san** [comment]
+1 !

**Comment by BdeHeij** [comment]
@leinaddm ?

**Comment by propyless** [comment]
Hey all, leinaddm has mentioned multiple times that he no longer has time to maintain this.

you  can find the module with this puppetv4 support @ gillarkod/puppet-htpasswd where it will most likely be maintained by someone there.

**Pull request closed without merging**
